version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/deployment
hooks:
  BeforeInstall:
    - location: scripts/stop_docker_container.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: scripts/start_docker_container.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/verify_docker_service.sh
      timeout: 300
      runas: root
